import { Manrope } from 'next/font/google'
import './globals.scss'
import Header from './components/Global/Header'
import Footer from './components/Global/Footer'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
